Plaza.Web/Areas/Admin/Controllers/ReservationsController.cs
using Line.Data;
using Line.Models;
using Line.Services;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Line.Helpers;

namespace Line.Controllers
{
    public class ReservationsController : AdminController
    {
        public ILanguageService _LanguageService;
        public ILocalizationService _LocalizationService;
        public IWorkContext _workContext;
        public IConfiqurationService _configurationService;
        public IReservationService _reservationService;
        public IReportsService _reportsService;
        public IAccountingService _accountingService;
        public IVisitorService _VisitorService;
        public IUploadService _uploadService;
        private readonly int PageSize = 50;

        public ReservationsController(ILanguageService languageService, ILocalizationService localizationService,
             IWorkContext workContext, IConfiqurationService configurationService, IVisitorService VisitorService,
            IReservationService reservationService, IReportsService reportsService, IAccountingService accountingService, IUploadService uploadService)
        {
            this._LanguageService = languageService;
            this._LocalizationService = localizationService;
            this._workContext = workContext;
            this._VisitorService = VisitorService;
            this._uploadService = uploadService;
            this._configurationService = configurationService;
            this._reservationService = reservationService;
            this._accountingService = accountingService;
            this._reportsService = reportsService;
        }
        public ActionResult QuickSearch(string qid)

        {
            int value;
            if (int.TryParse(qid, out value))
                return RedirectToAction("OpenReservations", new { Id = value });

            return RedirectToAction("Search");
        }

        public JsonResult GetAgencies(string q)
        {
            if (q.Count() >= 3)
            {
                var contents = new SelectList(_configurationService.Agencies().Select(x => new { Id = x.ID, name = x.AgencyName + ", " + x.City + ", " + x.Country })
                    .Where(d => d.name.ToLower().Contains(q.ToLower())), "Id", "name");
                return Json(contents, JsonRequestBehavior.AllowGet);
            }
            return Json("", JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetHotels(string q)
        {
            if (q.Count() >= 3)
            {
                var contents = new SelectList(_configurationService.SearchHotels(0).Select(x => new { Id = x.Id, name = x.name + ", " + x.city + ", " + x.country })
                    .Where(d => d.name.ToLower().Contains(q.ToLower())), "Id", "name");
                return Json(contents, JsonRequestBehavior.AllowGet);
            }
            return Json("", JsonRequestBehavior.AllowGet);
        }
        // GET: Admin/Reservations

        public ActionResult CreateReservations()
        {
            var selectagency = new List<SelectListItem>();
            ViewBag.Agencies = selectagency;
            return View(new ReservationControl());
        }
        [HttpPost]
        public ActionResult CreateReservations(ReservationControl Model)
        {
            ViewErrors errors = new ViewErrors();

            var agency = _configurationService.GetAgencyById(Model.AID);
            if (agency == null)
            {
                return PageNotFound();
            }

            var selectagency = new List<SelectListItem>();
            selectagency.Add(new SelectListItem { Text = agency.AgencyName, Value = Model.AID.ToString() });
            ViewBag.Agencies = selectagency;

            //we must create empty file to fill later 
            var reservation = CreateFileToAgency(agency);

            //check balance and limits
            var ress = agency.Reservations.Where(d => d.status == ReservationStatus.Confirmed.ToString() || d.status == ReservationStatus.ReConfirmed.ToString());
            var balance = ress.Sum(d => d.price) - ress.Sum(d=> d.Payments.Sum(x=> x.Payment)) - agency.AdvancePayment.Sum(d => d.Payment);
            var Credit = Convert.ToDecimal(agency.CreditAmount);
            //if (agency.Credit == CreditType.Cash.ToString())
            //{
            //    errors.Errors.Add("Cash");
            //    ViewBag.warning = errors;
            //    reservation.status = ReservationStatus.Locked.ToString();
            //    reservation.note = "Cash agency";

            //    if (!Model.CreateApproved)
            //    {
            //        return View(Model);
            //    }

            //}
            //else 
            if (agency.Credit == CreditType.Limited.ToString() && balance >= Credit)
            {
                errors.Errors.Add("Limited");
                errors.Errors.Add("Balance is : " + balance.ToString(true) + " Credit Ammount: " + Credit.ToString(true));
                ViewBag.warning = errors;
                reservation.status = ReservationStatus.Locked.ToString();
                reservation.note = "Balance is : " + balance.ToString(true) + " Credit Ammount: " + Credit.ToString(true);

                if (!Model.CreateApproved)
                {
                    return View(Model);
                }
            }
           


            var result = _reservationService.InsertReservation(reservation);
            if (result != null)
            {
                _reservationService.InsertFileNote(new Filelog { Action = "File Created: ", ref_file = result.ID, ref_member = result.ref_member, shortMessage = agency.AgencyName + " : New File" });
            }
            return RedirectToAction("OpenReservations", new { Id = result.ID });
        }


        public ActionResult LockedReservations()
        {
            var SearchModel = new ReservationSearchModel();

            SearchModel.Status.Add(ReservationStatus.Locked.ToString());
            if (!_workContext.IsAdmin)
            {
                SearchModel.CreatedBy.Add(_workContext.CurrentVisitor.Id);
            }
            var result = _reservationService.SearchReservations(SearchModel, false);

            return View(result);
        }

        public ActionResult Unlock(int Id)
        {
            var res = _reservationService.GetReservationById(Id);
            if (res == null)
            {
                return PageNotFound();
            }
            res.status = ReservationStatus.Request.ToString();
            _reservationService.UpdateReservation(res);
            _reservationService.InsertFileNote(new Filelog
            {
                Action = "File Unlocked",
                ref_file = res.ID,
                ref_member = _workContext.CurrentVisitor.Id,
                shortMessage = "File Unlocked by " + _workContext.CurrentVisitor.GetFullName()
            });
            return Json(new { success = true, responseText = "Unlocked" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ConfirmReservations(int cId, FormCollection form)
        {
            var note = form["cNote"];
            var email = form["cemail"];
            var cc = form["cemailcc"];
            var send = form["cSend"];
            var cSendInvoice = form["cSendInvoice"];
            var cSendVoucher = form["cSendVoucher"];
            
            var res = _reservationService.GetReservationById(cId);
            if (res == null)
            {
                return PageNotFound();
            }
            res.status = ReservationStatus.Confirmed.ToString();
            _reservationService.UpdateReservation(res);
            _reservationService.InsertFileNote(new Filelog
            {
                Action = "File Confirmed ",
                ref_file = res.ID,
                ref_member = _workContext.CurrentVisitor.Id,
                shortMessage = "File Confirmed by " + _workContext.CurrentVisitor.GetFullName()
            });

            var ccList = new List<string>();
            if (cc != null)
            {
                ccList = cc.Split(';').Where(d => !string.IsNullOrEmpty(d)).ToList();
            }

            if (!string.IsNullOrEmpty(send))
            {
                Mailing.SendMailToAgency(res.Agency.AgencyName, res.agencystaff, email, note, ccList,
                    res.Agency.AgencyName, _workContext.CurrentVisitor.GetFullName(), _workContext.CurrentVisitor.title, _workContext.CurrentVisitor.email, res, "",!string.IsNullOrEmpty(cSendInvoice), !string.IsNullOrEmpty(cSendVoucher));
            }

            return RedirectToAction("OpenReservations", new { Id = cId });
        }
        public ActionResult ReConfirmReservations(int rcId, FormCollection form)
        {
            var note = form["rcNote"];
            var email = form["rcemail"];
            var cc = form["rcemailcc"];
            var send = form["rcSend"];
            var voucher = form["rcvocher"];
            var rcHcn = form["rcHcn"];
            var res = _reservationService.GetReservationById(rcId);
            if (res == null)
            {
                return PageNotFound();
            }
            res.vocher = Request.Form["rcvocher"];
            res.HCN = rcHcn;
            res.status = ReservationStatus.ReConfirmed.ToString();
            _reservationService.UpdateReservation(res);


            if (!string.IsNullOrEmpty(rcHcn))
            {
                voucher = voucher + ", HCN: " + rcHcn;
            }

            var ccList = new List<string>();
            if (cc != null)
            {
                ccList = cc.Split(';').Where(d => !string.IsNullOrEmpty(d)).ToList();
            }

            if (!string.IsNullOrEmpty(send))
            {
                Mailing.SendMailToAgency(res.Agency.AgencyName, res.agencystaff, email, note, ccList,

Plaza.Web/Areas/Admin/Views/Reservations/CustomerSearch.cshtml
@model Line.Models.ReservationSearchModel
@using Line.Models
@{
    ViewBag.Title = "Search";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

    var results = (List<Line.Data.Reservations>)ViewBag.Reseult;

}



<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        @using (Html.BeginForm())
        {
            <div class="row">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12">
                            Results using guest name and file "check in" between search date...
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>@T("Reservations.Customer")</label>
                                @Html.TextBoxFor(d => d.Customer, new { @class = "form-control", @data_placeholder = @T("Customer.search") })
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label>@T("ignore.date")</label>
                                @Html.CheckBoxFor(d =>  d.OnlyPaidFiles, new { style = "width:30px ;height: 30px;display: block; " })
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label><strong>@T("date.from")</strong></label>
                                <div class="form-group" id="data_5">
                                    <div class="input-daterange input-group" id="datepicker">
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                        @Html.TextBoxFor(d => d.CreateDate, Model.CreateDate.ToShortDateString(), new { @class = "form-control", autocomplete = "off" })
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label><strong>@T("date.to")</strong></label>
                                <div class="form-group" id="data_5">
                                    <div class="input-daterange input-group" id="datepicker">
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                        @Html.TextBoxFor(d => d.CreateDateTo, Model.CreateDateTo.ToShortDateString(), new { @class = "form-control", autocomplete = "off" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 text-center">
                            <div style="margin-top:20px">
                                <input type="submit" class="btn btn-success" value="@T("Reservation.search")" />

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span>@T("Reservations.Results")</span>
                    @*<div class="ibox-tools">
                            <button type="button" class="btn btn-danger  btn-xs" data-toggle="modal" data-target=".bd-example-modal-lg">@T("Search")</button>
                        </div>*@
                </div>
                <div class="ibox-content">
                    <table id="datatabel" class="table table-striped">
                        <thead>
                            <tr>
                                <th></th>
                                <th>
                                    @T("Id")
                                </th>
                                <th>
                                    @T("Agency")
                                </th>
                                <th>
                                    @T("Country")
                                </th>
                                <th>
                                    @T("Service")
                                </th>
                                <th>
                                    @T("Total")
                                </th>
                                <th>
                                    @T("Checkin") -  @T("Checkout")
                                </th>
                                <th class="table-inputs"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var res in results)
                            {
                                <tr>
                                    <td></td>
                                    <td>
                                        @{
                                            var viewclass = "";
                                            switch (res.status)
                                            {
                                                case "Request":
                                                    viewclass = "btn-warning";
                                                    break;
                                                case "Confirmed":
                                                    viewclass = "btn-info";
                                                    break;
                                                case "ReConfirmed":
                                                    viewclass = "btn-success";
                                                    break;
                                                case "Canceled":
                                                    viewclass = "btn-danger";
                                                    break;
                                                case "Completed":
                                                    viewclass = "btn-primary";
                                                    break;
                                                default:
                                                    viewclass = "btn-warning";
                                                    break;
                                            }
                                        }
                                        <a href="@Url.Action("ViewReservations", "Reservations", new { id = res.ID })"><span class="btn btn-3d btn-xs @viewclass">#@res.ID</span></a>

                                    </td>
                                    <td>
                                        @res.Agency.AgencyName<br />
                                        @res.GetCustomers()
                                    </td>
                                    <td>
                                        @res.Agency.Country
                                    </td>
                                    <td>
                                        @if (res.Rhotel.Count > 0)
                                        {<span class="btn btn-primary btn-xs">@T("Hotel")</span>}
                                        @if (res.Transfers.Count > 0)
                                        {<span class="btn btn-primary btn-xs">@T("Transfers")</span>}
                                        @if (res.Flight.Count > 0)
                                        {<span class="btn btn-primary btn-xs">@T("Flight")</span>}
                                        @if (res.Tour
                                            .Count > 0)
                                        {<span class="btn btn-primary btn-xs">@T("Tour")</span>}
                                        @if (res.ExtraService
                                            .Count > 0)
                                        {<span class="btn btn-primary btn-xs">@T("Extra")</span>}
                                    </td>
                                    <td>
                                        @res.price.ToString(true)
                                    </td>
                                    <td>
                                        @res.checkindate.ToShortDateString() - @res.balanceDate.ToShortDateString()
                                    </td>
                                    <td>

                                        <a target="_blank" href='@Url.Action("OpenVocher", "Reservations", new { id = res.ID })' class="btn btn-info btn-sm">
                                            <span class="glyphicon glyphicon-print"></span>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                <th>

                                </th>
                                <th>

                                </th>
                                <th>

                                </th>
                                <th>

                                </th>
                                <th>
                                    @results.Sum(d => d.price).ToString(true)
                                </th>
                                <th>

                                </th>
                                <th class="table-inputs"></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>




@section Styles {
    @Styles.Render("~/Content/plugins/chosen/chosenStyles")
    @Styles.Render("~/plugins/select2Styles")
    @Styles.Render("~/plugins/dataPickerStyles")
    @Styles.Render("~/plugins/dateRangeStyles")
}


@section Scripts {
    @Scripts.Render("~/plugins/chosen")
    @Scripts.Render("~/plugins/select2")
    @Scripts.Render("~/plugins/dataPicker")
    @Scripts.Render("~/plugins/validate")
    @Scripts.Render("~/plugins/dateRange")

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>

    <script type="text/javascript">
        $('.input-daterange').datepicker({
            todayBtn: "linked",
            format: "dd.mm.yyyy",
            startView: 1,
            daysOfWeekHighlighted: "0,6"
        });

        $('.chosen-select-members').chosen({ width: "100%" });

        $('.js-data-example-ajax').select2({
            minimumInputLength: 3,
            ajax: {
                url: '/Admin/Reservations/GetAgencies',
                dataType: 'json',
                delay: 250,
                data: function (params) {
                    return {
                        q: params.term, // search term
                    };
                },
                processResults: function (data) {
                    return {
                        results: $.map(data, function (obj) {
                            return { id: obj.Value, text: obj.Text };
                        })
                    };
                }
            }
        });
    </script>
    <script type="text/javascript">

          $(document).ready(function () {
                $('#datatabel').DataTable({
                    responsive: {
                        details: {
                            type: 'column',
                            target: 'tr'
                        }
                    },
                    columnDefs: [{
                        className: 'control',
                        orderable: false,
                        targets: 0
                    }],
                    order: [1, 'asc'],
                    dom: 'Bfrtip',
                    buttons: [
                        'print', 'excel', 'pdf'
                    ]
                });
            });

    </script>

}

Plaza.Web/Areas/Admin/Views/Reservations/ReservationHotels.cshtml
@model Line.Models.HotelsviewModel
@{
    ViewBag.Title = "ReservationHotels";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    .modal-dialog {
        width: 1000px;
    }
</style>

    <div class="row white-bg p-xs">
        <div class="col-lg-2">
            <b>@T("Reservation Id")</b>
            <p>
                <a href='@Url.Action("OpenReservations", "Reservations", new { id = Model.RID })' class="btn btn-primary btn-xs">
                    # @Model.RID
                </a>
            </p>
        </div>
        <div class="col-lg-2">
            <b>@T("Reservation Owner")</b>
            <p> @Model.Owner </p>
        </div>
        <div class="col-lg-2">
                <b>@T("Agency name")</b>
                <p>@Model.Agency</p>
        </div>
        <div class="col-lg-2">
            <b>Total</b>
            <p class="text-danger">@Model.Total</p>
        </div>
        <div class="col-lg-4">
            <b>@T("hotels")</b>
            <p>
                @T("hotels.reservation.new")
            </p>
        </div>

    </div>

@using (Html.BeginForm())
{
    @Html.HiddenFor(d => d.RID)
    <div class="row white-bg p-xs">
        <div class="col-lg-6">
            <p><b>@T("hotel.Search")</b></p>
            <div class="form-group">
                @Html.DropDownListFor(d => d.hotel, (List<SelectListItem>)ViewBag.Hotels, new { @class = "form-control js-data-example-ajax ", required="required" })
            </div>
        </div>
        <div class="col-lg-6">
            <p><b></b></p><br />
            <input type="submit" class="btn btn-sm btn-info" name="name" value="@T("hotel.select")" />
        </div>
    </div>
}


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <table id="datatabel" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th width="40"></th>
                                        <th></th>
                                        <th>@T("Hotel")</th>
                                        <th>@T("Checkin-Checkout")</th>
                                        <th>@T("Rooms")</th>
                                        <th>@T("Status")</th>
                                        <th>@T("Total")</th>
                                    </tr>
                                </thead>
                                <tbody>


                                    @foreach (var item in Model.Hotles)
                                    {
                                        <tr>
                                            <td></td>
                                            <td>
                                                <a href="#" class="btn btn-danger btn-xs" onclick="deleteHotel(@item.ID)"><i class="fa fa-trash"></i></a>
                                                <a href="@Url.Action("ReservationRooms",new {Id= item.ID })" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i></a>
                                            </td>
                                            <td>
                                                @item.name @*(@item.rate @T("Stars"))*@
                                            </td>
                                            <td>@item.checkin.ToShortDateString() - @item.checkout.ToShortDateString()</td>
                                            <td>@item.RHRoom.Count</td>
                                            <td>@item.Confirmed</td>
                                            <td>
                                                @item.Total.ToString(true) 
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@Html.Partial("_ConfirmDelete", "deletedialog")


@section Styles {
    @Styles.Render("~/Content/plugins/chosen/chosenStyles")
    @Styles.Render("~/plugins/select2Styles")
}


@section Scripts {
    @Scripts.Render("~/plugins/chosen")
    @Scripts.Render("~/plugins/select2")


    <script type="text/javascript">

        $('.js-data-example-ajax').select2({
            minimumInputLength: 3,
            ajax: {
                url: '/Admin/Reservations/GetHotels',
                dataType: 'json',
                delay: 250,
                data: function (params) {
                    return {
                        q: params.term, // search term
                    };
                },
                processResults: function (data) {
                    return {
                        results: $.map(data, function (obj) {
                            return { id: obj.Value, text: obj.Text };
                        })
                    };
                }
            }
        });

        function deleteHotel(Id) {
        $('#deletedialog').modal({
                backdrop: 'static',
                keyboard: false
            })
            .one('click', '#delete', function (e) {

                    $.ajax({
                        url: "@Url.Action("DeleteHotel", "Reservations", new { Area = "Admin" })",
                        type: "Post",
                        data: JSON.stringify({ 'Id': Id }),
                        dataType: "json",
                        traditional: true,
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            toastr.info("@T("Confirmed")")
                            location.reload();
                        },
                        error: function () {
                            alert("An error has occured!!!");
                        }
                    });
                });
    }




    </script>
    <script>
        $(document).ready(function () {
            $('#datatabel').DataTable({
                "paging": false,
                "ordering": false,
                "info": false,
                "bFilter": false,
                responsive: {
                    details: {
                        type: 'column',
                        target: 'tr'
                    }
                },
                columnDefs: [{
                    className: 'control',
                    orderable: false,
                    targets: 0
                }],
                order: [1, 'asc'],
            });
        });

    </script>
}