Plaza.Web/Areas/Admin/Controllers/AccountingController.cs
using Line.Models;
using Line.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Line.Helpers;

namespace Line.Controllers
{
    public class AccountingController : AdminController
    {
        public ILanguageService _LanguageService;
        public ILocalizationService _LocalizationService;
        public IWorkContext _workContext;
        public IConfiqurationService _configurationService;
        public IReservationService _reservationService;
        public IReportsService _reportsService;
        public IAccountingService _accountingService;
        public IVisitorService _VisitorService;
        public IUploadService _uploadService;
        private readonly int PageSize = 50;

        public AccountingController(ILanguageService languageService, ILocalizationService localizationService,
             IWorkContext workContext, IConfiqurationService configurationService, IVisitorService VisitorService,
            IReservationService reservationService, IReportsService reportsService, IAccountingService accountingService, IUploadService uploadService)
        {
            this._LanguageService = languageService;
            this._LocalizationService = localizationService;
            this._workContext = workContext;
            this._VisitorService = VisitorService;
            this._uploadService = uploadService;
            this._configurationService = configurationService;
            this._reservationService = reservationService;
            this._accountingService = accountingService;
            this._reportsService = reportsService;
        }
        // GET: Admin/Accounting


        public ActionResult Agencies(int Id = 0)
        {
            var Model = new AgencyViewModel();
            Model.Agency = _configurationService.GetAgencyById(Id);
            if (Model.Agency != null)
            {
                ViewBag.Agencies = new List<SelectListItem> { new SelectListItem { Text = Model.Agency.AgencyName, Value = Model.Id.ToString(), Selected = true } };
                var SearchModel = new ReservationSearchModel();
                SearchModel.CheckoutDatefrom = Model.CheckOutFrom;
                SearchModel.CheckoutDateto = Model.CheckOutTo;
                SearchModel.AgencyId = new List<int> { Model.Id };
                var result = _reservationService.SearchReservations(SearchModel, true).ToList();
                Model.Files = result;
            }
            else
            {
                ViewBag.Agencies = new List<SelectListItem>();
            }
            return View(Model);
        }

        public ActionResult DownloadExcel(int Id = 0)
        {
            var Model = _reportsService.GetDebtReport("");
            Export export = new Export();
            export.ToExcel(Response, Model,"Debts");

            return Content("");
        }

        public ActionResult DownloadAgencyExcel(int Id = 0)
        {

            var Model = new AgencyViewModel();
            var SearchModel = new ReservationSearchModel();

            Model.CheckOutFrom = DateTime.MinValue;
            Model.CheckOutTo = DateTime.MaxValue;

            SearchModel.AgencyId = new List<int> { Id };
            var result = _reservationService.SearchReservations(SearchModel, true).ToList();

            var ViewMode = result.OrderByDescending(d => d.ID).Select(d =>
            new
            {
                Id = d.ID,
                Voucher = d.vocher,
                Dates = d.checkindate.ToShortDateString() + " - " + d.balanceDate.ToShortDateString(),
                Guest = d.GetCustomers(),
                Debt = d.price,
                Payment = d.Payments.Sum(x => x.Payment),
                Balance = d.price - d.Payments.Sum(x => x.Payment)
            });

            var agency = _configurationService.GetAgencyById(Id);
            Export export = new Export();
            export.ToExcel(Response, ViewMode, agency.AgencyName);

            return Content("");
        }

        public ActionResult Statement(int Id, string Statement)
        {
            var model = new StatmentViewModel();
            var agency = _configurationService.GetAgencyById(Id);
            model.Id = agency.ID;
            model.City = agency.City;
            model.Country = agency.Country;
            model.name = agency.AgencyName;

            model.Statment = Statement.ToUpper();

            if (Statement == "A") //unpaid
            {
                var SearchModel = new ReservationSearchModel { AgencyId = new List<int> { model.Id } };

                var files = _reservationService.SearchReservations(SearchModel, true).Where(d => d.balance != 0);

                model.Files = files.Select(x => new DeptDateViewModel { Id = x.ID, name = x.vocher, Country = x.Agency.Country, City = x.Agency.City, DebtValue = x.price, BalanceValue = x.balance, PaymentsValue = x.Payments.Sum(p => p.Payment), Cutomer = x.GetCustomers(), date = x.checkindate.ToString("dd.MM.yyyy") + " - " + x.balanceDate.ToString("dd.MM.yyyy") }).ToList();

            }
            if (Statement == "B") //passed
            {
                var SearchModel = new ReservationSearchModel { AgencyId = new List<int> { model.Id } };
                SearchModel.CheckoutDateto = DateTime.Today.Date;
                SearchModel.CheckoutDatefrom = DateTime.MinValue.AddDays(1);

                var files = _reservationService.SearchReservations(SearchModel, true).Where(d => d.balance != 0);

                model.Files = files.Select(x => new DeptDateViewModel { Id = x.ID, name = x.vocher, Country = x.Agency.Country, City = x.Agency.City, DebtValue = x.price, BalanceValue = x.balance, PaymentsValue = x.Payments.Sum(p => p.Payment), Cutomer = x.GetCustomers(), date = x.checkindate.ToString("dd.MM.yyyy") + " - " + x.balanceDate.ToString("dd.MM.yyyy") }).ToList();

            }
            if (Statement == "C") //future
            {
                var SearchModel = new ReservationSearchModel { AgencyId = new List<int> { model.Id } };
                SearchModel.CheckoutDatefrom = DateTime.Today.AddDays(1).Date;
                SearchModel.CheckoutDateto = DateTime.MaxValue;

                var files = _reservationService.SearchReservations(SearchModel, true).Where(d => d.balance != 0);

                model.Files = files.Select(x => new DeptDateViewModel { Id = x.ID, name = x.vocher, Country = x.Agency.Country, City = x.Agency.City, DebtValue = x.price, BalanceValue = x.balance, PaymentsValue = x.Payments.Sum(p => p.Payment), Cutomer = x.GetCustomers(), date = x.checkindate.ToString("dd.MM.yyyy") + " - " + x.balanceDate.ToString("dd.MM.yyyy") }).ToList();

            }

            if (agency.Country.ToLower().Contains("lebanon")
                || agency.Country.ToLower().Contains("lb")

                )
            {
                return View("Statement2", model);
            }
            else
            {
                return View(model);
            }

        }
        [HttpPost]
        public ActionResult Agencies(AgencyViewModel Model)
        {
            return RedirectToAction("Agency", new { Id = Model.Id });
        }

        public ActionResult Agency(int Id, AgencyViewModel Model, int page = 1)
        {

            var SearchModel = new ReservationSearchModel();

            if (Request.HttpMethod == "POST") { page = 1; }
            if (Model.CheckOutFrom == Model.CheckOutTo) { Model.CheckOutFrom = DateTime.Now.AddMonths(-1); Model.CheckOutTo = DateTime.Now; }

            if (Model.Showpayment)
            {
                SearchModel.CheckoutDatefrom = Model.CheckOutFrom;
                SearchModel.CheckoutDateto = Model.CheckOutTo;
            }
            else
            {
                if (Model.FileDate == 0)
                {//future

                    SearchModel.CheckoutDatefrom = DateTime.Now.Date;
                    SearchModel.CheckoutDateto = DateTime.MaxValue;
                }
                else if (Model.FileDate == 1) // old
                {
                    SearchModel.CheckoutDatefrom = DateTime.MinValue;
                    SearchModel.CheckoutDateto = DateTime.Now.Date;
                }
            }

            SearchModel.AgencyId = new List<int> { Id };

            if (Model.FileStatus == 1)
            {
                SearchModel.OnlyPaidFiles = true;
            }
            else if (Model.FileStatus == 0)
            {
                SearchModel.OnlyUnpaidFiles = true;
            }

            var result = _reservationService.SearchReservations(SearchModel, false);


            var canceled = result.Where(d => d.status == ReservationStatus.Canceled.ToString()).ToList();
            result = result.Where(d => d.status == ReservationStatus.Confirmed.ToString() || d.status == ReservationStatus.ReConfirmed.ToString()).ToList();
            Model.Agency = _configurationService.GetAgencyById(Id);
            ViewBag.Canceled = canceled;

            ViewBag.Filter = Model;
            var income = Model.Agency.AdvancePayment.Where(d => !d.PayOut).Sum(d => d.Payment);
            var Outcome = Model.Agency.AdvancePayment.Where(d => d.PayOut).Sum(d => d.Payment);
            ViewBag.advancePayments = income - Outcome;

            return View(result.OrderByDescending(d => d.balanceDate).ToPagedList(page, PageSize));

        }
        public ActionResult Debts(int page = 1)
        {
            var Model = new ReservationSearchModel();
            Model.CheckoutDateto = DateTime.Today.Date;
            Model.CheckoutDatefrom = DateTime.MinValue.AddDays(1);
            Model.OnlyUnpaidFiles = true;
            var result = _reservationService.SearchReservations(Model, true);

Plaza.Web/Areas/Admin/Controllers/ReportsController.cs
using Line.Models;
using Line.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Line.Controllers
{
    public class ReportsController : AdminController
    {

        public ILanguageService _LanguageService;
        public ILocalizationService _LocalizationService;
        public IWorkContext _workContext;
        public IConfiqurationService _configurationService;
        public IReservationService _reservationService;
        public IReportsService _reportsService;
        public IAccountingService _accountingService;
        public IVisitorService _VisitorService;
        public IUploadService _uploadService;

        public ReportsController(ILanguageService languageService, ILocalizationService localizationService,
             IWorkContext workContext, IConfiqurationService configurationService, IVisitorService VisitorService,
            IReservationService reservationService, IReportsService reportsService, IAccountingService accountingService, IUploadService uploadService)
        {
            this._LanguageService = languageService;
            this._LocalizationService = localizationService;
            this._workContext = workContext;
            this._VisitorService = VisitorService;
            this._uploadService = uploadService;
            this._configurationService = configurationService;
            this._reservationService = reservationService;
            this._accountingService = accountingService;
            this._reportsService = reportsService;
        }


        // GET: Admin/Reports
        public ActionResult Dashboard()
        {
            //if (_reportsService.Getlastyear() < DateTime.Now.Year)
            //{
            //    if (_reportsService.Getlastyear() + 1 == DateTime.Now.Year)
            //    {

            //    }
            //    else
            //    {
            //        for (int i = _reportsService.Getlastyear(); i < DateTime.Now.Year - 1; i++)
            //        {
            //            _reportsService.UpdateReportTable(i + 1);
            //        }
            //    }
            //}

            var Search = new ReservationSearchModel();
            //get last 2 years,
            Search.CheckinDatefrom = new DateTime(DateTime.Now.Year - 1, 1, 1);
            Search.CheckinDateto = new DateTime(DateTime.Now.Year + 1, 1, 1);
            var Reservations = _reservationService.SearchReservations(Search, true);

            DashboardViewModel Model = new DashboardViewModel();

            Model.Sales = _reportsService.GetSalesByRegistrations(Reservations);
            Model.Years = _reportsService.GetYearsDashboard();

            Model.Agencies = _reportsService.GetAgencyReport(DateTime.Now.Year, Reservations);
            Model.AgenciesLastYear = _reportsService.GetAgencyReport(DateTime.Now.Year - 1, Reservations);


            var countries = _reportsService.GetCountriesReport(Reservations);
            Model.Countries = countries.Where(d => d.Year == DateTime.Now.Year).OrderByDescending(v => v.Sales).Take(15).ToList();
            Model.CountriesLastYear = countries.Where(d => d.Year == DateTime.Now.Year - 1).OrderByDescending(v => v.Sales).Take(15).ToList();

            Model.Hotels = _reportsService.GetHotelsReport(DateTime.Now.Year, Reservations);
            Model.HotelsLastYear = _reportsService.GetHotelsReport(DateTime.Now.Year - 1, Reservations);

            return View(Model);
        }


        public ActionResult Sales()
        {
            
            ViewBag.CountChart = _reportsService.GetSalesFilesCounters(DateTime.Now.Year);

            ViewBag.SalesChart = _reportsService.GetSales(DateTime.Now.Year - 1);

            var Model = _reportsService.GetSales(DateTime.Now.AddYears(-4).Year);

            return View(Model);
        }

        public ActionResult Profit()
        {
            ViewBag.CountChart = _reportsService.GetSalesFilesCounters(DateTime.Now.Year);

            ViewBag.SalesChart = _reportsService.GetProfits(DateTime.Now.Year - 1);

            var Model = _reportsService.GetProfits(DateTime.Now.AddYears(-4).Year);

            return View(Model);
        }

        public ActionResult Countries()
        {

            ViewBag.Countries = _configurationService.GetUsedCountries("");

            var Search = new ReservationSearchModel();
            //get last 4 years,
            Search.CheckinDatefrom = new DateTime(DateTime.Now.Year - 3, 1, 1);
            Search.CheckinDateto = new DateTime(DateTime.Now.Year + 1, 1, 1);
            var Reservations = _reservationService.SearchReservations(Search, true);


            var Model = Reservations.GroupBy(d => new { d.Agency.Country, d.balanceDate.Year })
            .Select(x => new ShortReport
            {
                Year = x.Key.Year,
                Name = x.Key.Country,
                Count = x.Count(),
                Sales = x.Sum(c => c.price)
            });
           

            return View(Model);
        }

        public ActionResult Agencies()
        {
            var country = Request.QueryString["country"];
            if (string.IsNullOrEmpty(country))
            {
                return RedirectToAction("Countries");
            }
            //ViewBag.Counters = _reportsService.GetCountryFilesCounters(DateTime.Now.Year, country);
            var Model = _reportsService.GetAgencyReportByCountry(DateTime.Now.Year - 4, country);
            return View(Model);

        }

        public ActionResult Agency()
        {
            var Id = Request.QueryString["AId"];
            var agency = _configurationService.GetAgencyById(Convert.ToInt32(Id));
            if (agency != null)
            {
                ViewBag.Counters = _reportsService.GetAgencyFilesCounters(DateTime.Now.Year, Convert.ToInt32(Id));
                var Model = _reportsService.GetAgencyReportById(2015, Convert.ToInt32(Id));
                ViewBag.Name = agency.AgencyName;
                return View(Model);

            }

            return RedirectToAction("Countries");


        }

        public ActionResult Member(int Id)
        {
            ViewBag.Counters = _reportsService.GetStaffFilesCounters(DateTime.Now.Year, Id);
            var Model = _reportsService.GetAgencyReportByMemberId(2015, Id);
            return View(Model);
        }

        public ActionResult Hotels()
        {
            //ViewBag.Graph = _reportsService.GetCountriesReport(DateTime.Now.Year);
            var Model = new List<ShortReport>();
            for (int i = DateTime.Now.Year - 1; i <= DateTime.Now.Year; i++)
            {
                Model.AddRange(
                    _reportsService.GetHotelsReport(i)
                );
            }
            return View(Model);

        }

        public ActionResult staff()
        {
            ViewBag.CountChart = _reportsService.GetSalesFilesCounters(DateTime.Now.Year);
            ViewBag.SalesChart = _reportsService.GetSales(DateTime.Now.Year-1);

            var Search = new ReservationSearchModel();
            //get Current year,
            Search.CreateDate = new DateTime(DateTime.Now.Year, 1, 1);
            Search.CreateDateTo = new DateTime(DateTime.Now.Year + 1, 1, 1);
            var Reservations = _reservationService.SearchReservations(Search, true);
            var model = _reportsService.GetSalesByStaff(Reservations);
            return View(model);
        }

        public ActionResult AgenciesInfo(string country = "")
        {
            ViewBag.Countries = _configurationService.GetUsedCountries(country);
            var List = _configurationService.SearchAgencies(0);
            if (country != null)
            {
                List = List.Where(d => d.Country == country).ToList();
            }
            return View(List);
        }

        public ActionResult DeptsCountries(string name = "")
        {
            return View();
        }

        public ActionResult DeptAgencies(int Id = 0)
        {
            return View();
        }

    }


}

Plaza.Web/Areas/Admin/Views/Accounting/AdvancePayments.cshtml
@model PagedList.PagedList<Line.Data.AdvancePayments>
@{
    /**/

    ViewBag.Title = "Files";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

    int RId = (int)ViewBag.AgencyId;
}

@using Line.Models

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2>
            @T("Advance.Payment.header")
        </h2>
    </div>
    <div class="col-lg-12">
        @using (Html.BeginForm())
        {
            <div class="row">
                <div class="col-lg-12">
                    <b>@ViewBag.Agency</b>
                </div>

                <div class="col-lg-5" id="sandbox-container">
                    <div class="input-daterange  input-group">
                        <b>@T("Checkout.from") </b> <br />
                        @Html.TextBox("DateFrom", "", new { @class = "form-control date", name = "start", autocomplete = "off" })
                        <span class="input-group-addon" style="background-color:#fff"></span>
                        <b>@T("Checkout.to") </b> <br />
                        @Html.TextBox("DateTo", "", new { @class = "form-control date", name = "end", autocomplete = "off" })
                    </div>
                </div>
                <div class="col-lg-2">
                    <br />
                    <input type="submit" class="btn  btn-info" name="name" value="@("Search")" />
                </div>
            </div>
        }
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <button type="button" onclick="Payment()" class="btn btn-xs btn-success" name="name" ><i class="fa fa-plus"></i> @T("add.advance.payment")</button>
                </div>
                <div class="ibox-content">

                    <table class="table table-striped">

                        <tr>
                            <th>
                                @T("Id")
                            </th>
                            <th>
                                @T("Date")
                            </th>
                            <th>
                                @T("type")
                            </th>
                            <th>
                                @T("note")
                            </th>
                           
                            <th>
                                @T("Payments")
                            </th>
                            <th class="table-inputs"></th>
                        </tr>

                        @foreach (var res in Model)
                        {
                            string pclass = "";
                            if (res.PayOut)
                            {
                                pclass = "text-danger";
                            }
                        <tr class="@pclass">
                            <td>
                                @res.ID
                            </td>
                            <td>
                                @res.date.ToShortDateString()
                            </td>
                            <td>
                                @res.type
                            </td>
                            <td>
                                @res.note
                            </td>
                            <td>
                                @res.Payment
                            </td>
                            <td>
                                @if (!res.PayOut)
                                {
                                    <a type="button" href='@Url.Action("DeleteAdvancePayment", "Accounting", new { id = res.ID })' class="btn btn-danger btn-sm">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </a>
                                }

                                @*<a type="button" href='@Url.Action("CloseFiles", "Reservations", new { id = res.Agency.ID })' class="btn btn-danger btn-sm">
            <span class="glyphicon glyphicon-usd"></span>
        </a>*@
                            </td>
                        </tr>
                        }
                        <tfoot>
                            <tr>

                                <th>

                                </th>
                                <th>

                                </th>
                                <th>

                                </th>
                                <th>

                                </th>
                              
                               
                                <th>
                                    @Model.Sum(d => d.Payment).ToString(true)
                                </th>
                                <th class="table-inputs"></th>
                            </tr>

                        </tfoot>

                    </table>

                </div>
            </div>
        </div>
    </div>
</div>


<div id="Payment" class="modal fade" role="dialog">
    <div class="modal-dialog modal-dialog-sm">
        <div class="modal-content">
            @using (Html.BeginForm("AdvancePayment", "accounting", FormMethod.Post, new { Id = RId }))
            {
                @Html.Hidden("Id",RId)
                <div class="modal-header btn-info">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"> <span class="glyphicon glyphicon-send"></span> @T("Insert.AdvancePayment")</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <label>PaymentsValue: </label>
                            <div class="input-group input-group">
                                <span class="input-group-addon"></span>
                                <input type="number" id="PaymentsValue" class="form-control " min="0" max="" name="PaymentsValue" value="0" />
                            </div>
                            <label>Date: </label>
                            <div class="input-group input-group">
                                <span class="input-group-addon"></span>
                                <input type="text" id="date" class="form-control date" name="date" value="@DateTime.Today.ToString("dd.MM.yyyy")" />
                            </div>

                        </div>
                        <div class="col-lg-6">
                            <label>Type: </label>
                            <div class="input-group input-group">
                                <span class="input-group-addon"></span>
                                <select id="type" name="type" class="form-control" onchange="Control()">
                                    <option value="Credit Card">@T("Credit Card")</option>
                                    <option value="Cash">@T("Cash")</option>
                                    <option value="Bank Transfer">@T("Bank Transfer")</option>
                                    <option value="Credit Note">@T("Credit Note")</option>
                                    <option value="Draft">@T("Refund")</option>
                                </select>
                            </div>

                            <label>@T("auto.close.unpaid.files") </label>
                            <div class="input-group input-group">
                                <span class="input-group-addon">
                                    <input type="checkbox" checked="checked" id="autoclose" class="" name="autoclose">
                                </span>
                                <input type="text" id="desc" class="form-control" disabled name="desc" value="@T("Auto.Close.desc")" />
                            </div>
                        </div>
                    </div>
                    <label>Note:  </label>
                    <div class="input-group input-group">
                        <span class="input-group-addon"></span>
                        <textarea rows="5" cols="20" id="description" class="form-control " name="description" value=""></textarea>
                    </div>
                </div>
                <div class="modal-footer text-center">
                    <input type="submit" class="btn btn-info" name="confirm" value="@T("Make.Payment")" />
                    <input type="button" class="btn btn-danger" name="cancel" data-dismiss="modal" value="@T("Close")" />
                </div>
            }
        </div>
    </div>
</div>
@Html.Partial("_ConfirmDelete", "deletedialog")
@section Styles {
    @Styles.Render("~/plugins/dateRangeStyles")
    @Styles.Render("~/plugins/dataPickerStyles")
    @Styles.Render("~/plugins/select2Styles")
}


@section Scripts {
    @Scripts.Render("~/plugins/validate")
    @Scripts.Render("~/plugins/dataPicker")
    @Scripts.Render("~/plugins/dateRange")
    @Scripts.Render("~/plugins/select2")


    <script type="text/javascript">

        //$(document).ready(function () {

        //    $("#CheckOutFrom").val($("#Datefrom").val());
        //    $("#CheckOutTo").val($("#Dateto").val());

        //    $("#Datefrom").change(function () {
        //        $("#CheckOutFrom").val($("#Datefrom").val());
        //    });
        //    $("#Dateto").change(function () {
        //        $("#CheckOutTo").val($("#Dateto").val());
        //    });
        //});

        function togglePayments(Id) {
            $("#File-" + Id).toggle();
        }

      

        $('#sandbox-container .input-daterange').datepicker({
            format: "dd.mm.yyyy",
            daysOfWeekHighlighted: "0,6"
        });
        $('.date').datepicker({
            format: "dd.mm.yyyy",
            daysOfWeekHighlighted: "0,6"
        });


        function Payment(id, total) {
            $('#Payment').modal({
                backdrop: 'static',
                keyboard: false
            })
        }


        //$('#PaymentsValue').on('keydown keyup', function (e) {

        //    if (parseInt($(this).val() )> $("#PaymentsValue").attr("max")
        //        && e.keyCode !== 46 // keycode for delete
        //        && e.keyCode !== 8 // keycode for backspace
        //    ) {
        //        e.preventDefault();
        //        $(this).val($("#PaymentsValue").attr("max"));
        //    }
        //});




        function removepayment(id) {

        $('#deletedialog').modal({
            backdrop: 'static',
            keyboard: false
        })
            .one('click', '#delete', function (e) {
                $.ajax({
                    url: "@Url.Action("DeleteAdvancePayment", "Accounting", new { Area = "Admin" })",
                    type: "Post",
                    data: JSON.stringify({ 'id': id }),
                    dataType: "json",
                    traditional: true,
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        if (data.success == true) {
                              swal('@T("item.removed")')
                            location.reload();
                        } else {
                            alert("Error occurs on the Database level!");
                        }
                    },
                    error: function () {
                        alert("An error has occured!!!");
                    }
                });
            });
    }
    </script>

}