Plaza.Web/Controllers/CommonController.cs
using Line.Data;
using Line.Models;
using Line.Services;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Line.Controllers
{
    

    public class CommonController : Controller
    {

        public ILanguageService _LanguageService;
        public ILocalizationService _LocalizationService;
        public IWorkContext _workContext;
        public IConfiqurationService _configurationService;
        public IVisitorService _VisitorService;
        public IUploadService _uploadService;


        public CommonController(ILanguageService languageService, ILocalizationService localizationService,
         IWorkContext workContext, IConfiqurationService configurationService, IVisitorService VisitorService,  IUploadService uploadService)
        {
            this._LanguageService = languageService;
            this._LocalizationService = localizationService;
            this._workContext = workContext;
            this._configurationService = configurationService;
            this._VisitorService = VisitorService;
            this._uploadService = uploadService;
        }

        public ActionResult SetLanguage(int langid, string returnUrl = "")
        {
            var language = _LanguageService.GetLanguageById(langid);
            if (language != null && language.Published)
            {
                _workContext.WorkingLanguage = language;
            }

            //home page
            if (String.IsNullOrEmpty(returnUrl))
                returnUrl = Url.RouteUrl("HomePage");

            //prevent open redirection attack
            if (!Url.IsLocalUrl(returnUrl))
                returnUrl = Url.RouteUrl("HomePage");

            return Redirect(returnUrl);
        }

        public ActionResult LanguageSelector()
        {

            var availableLanguages = _LanguageService
                    .GetAllLanguages()
                    .ToList();


            var model = new LanguageSelectorModel
            {
                CurrentLanguageId = _workContext.WorkingLanguage.Id,
                AvailableLanguages = availableLanguages,
            };

            if (model.AvailableLanguages.Count == 1)
                Content("");

            return PartialView(model);
        }

        public ActionResult navheader()
        {
            var visitor = _workContext.CurrentVisitor;
           
            var profile = visitor.ToMiniModel();

            return PartialView(profile);
        }

        [HttpPost]
        //do not validate request token(XSRF)
        public ActionResult AsyncUpload()
        {
            //if (!_permissionService.Authorize(StandardPermissionProvider.UploadPictures))
            //    return Json(new { success = false, error = "You do not have required permissions" }, "text/plain");
            //we process it distinct ways based on a browser
            //find more info here http://stackoverflow.com/questions/4884920/mvc3-valums-ajax-file-upload
            Stream stream = null;
            var fileName = "";
            var contentType = "";
            if (String.IsNullOrEmpty(Request["qqfile"]))
            {
                // IE
                HttpPostedFileBase httpPostedFile = Request.Files[0];
                if (httpPostedFile == null)
                    throw new ArgumentException("No file uploaded");
                stream = httpPostedFile.InputStream;
                fileName = Path.GetFileName(httpPostedFile.FileName);
                contentType = httpPostedFile.ContentType;
            }
            else
            {
                //Webkit, Mozilla
                stream = Request.InputStream;
                fileName = Request["qqfile"];
            }

            var fileBinary = new byte[stream.Length];
            stream.Read(fileBinary, 0, fileBinary.Length);

            MemoryStream ms = new MemoryStream(fileBinary);
            System.Drawing.Image originalImage = System.Drawing.Image.FromStream(ms);

            if (originalImage.PropertyIdList.Contains(0x0112))
            {
                int rotationValue = originalImage.GetPropertyItem(0x0112).Value[0];
                switch (rotationValue)
                {
                    case 1: // landscape, do nothing
                        break;

                    case 8: // rotated 90 right
                            // de-rotate:
                        originalImage.RotateFlip(rotateFlipType: System.Drawing.RotateFlipType.Rotate270FlipNone);
                        break;

                    case 3: // bottoms up
                        originalImage.RotateFlip(rotateFlipType: System.Drawing.RotateFlipType.Rotate180FlipNone);
                        break;

                    case 6: // rotated 90 left
                        originalImage.RotateFlip(rotateFlipType: System.Drawing.RotateFlipType.Rotate90FlipNone);
                        break;
                }
            }


            var fileExtension = Path.GetExtension(fileName);
            if (!String.IsNullOrEmpty(fileExtension))
                fileExtension = fileExtension.ToLowerInvariant();
            //contentType is not always available 
            //that's why we manually update it here
            //http://www.sfsu.edu/training/mimetype.htm
            if (String.IsNullOrEmpty(contentType))
            {
                switch (fileExtension)
                {
                    case ".bmp":
                        contentType = MimeTypes.ImageBmp;
                        break;
                    case ".gif":
                        contentType = MimeTypes.ImageGif;
                        break;
                    case ".jpeg":
                    case ".jpg":
                    case ".jpe":
                    case ".jfif":
                    case ".pjpeg":
                    case ".pjp":
                        contentType = MimeTypes.ImageJpeg;
                        break;
                    case ".png":
                        contentType = MimeTypes.ImagePng;
                        break;
                    case ".tiff":
                    case ".tif":
                        contentType = MimeTypes.ImageTiff;
                        break;
                    default:
                        break;
                }
            }

            Line.Data.Picture picture = _uploadService.UploadImage(CopyImageToByteArray(originalImage), Path.GetFileNameWithoutExtension(fileName), fileExtension, contentType, URLType.upload);
            //when returning JSON the mime-type must be set to text/plain
            //otherwise some browsers will pop-up a "Save As" dialog.
            return Json(new
            {
                success = true,
                pictureId = picture.Id,
                imageUrl = picture.url
            },
                MimeTypes.TextPlain);
        }

        public static byte[] CopyImageToByteArray(System.Drawing.Image theImage)
        {
            using (MemoryStream memoryStream = new MemoryStream())
            {
                theImage.Save(memoryStream, System.Drawing.Imaging.ImageFormat.Png);
                return memoryStream.ToArray();
            }
        }
    }
}

Plaza.Web/Views/Shared/_ConfirmDelete.cshtml
@model string
<div class="modal inmodal" id="@Model" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated fadeIn">
            <div class="modal-body">
                <div class="row">
                    <h3 class="text-center">@T("Confirm.delete")</h3>
                    <hr />
                    <div class="text-center">
                        <button type="button" class="btn btn-white" data-dismiss="modal">@T("Close")</button>
                        <button type="button" data-dismiss="modal" class="btn btn-danger" id="delete">@T("delete")</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Plaza.Web/Views/Shared/_Footer.cshtml
<hr class="clearfix hidden-print" />
<div class="footer  hidden-print">
    <div class="pull-right">



    </div>
    <div>
        <strong>Copyright</strong>  plazadmc.com  &copy; 2017 - @DateTime.Now.Year
    </div>
</div>

Plaza.Web/Views/Shared/_RightSidebar.cshtml
<div id="right-sidebar">
    <div class="sidebar-container">
        <ul class="nav nav-tabs navs-3">
            <li class="active"><a data-toggle="tab" href="#Deadline">Deadline Date</a></li>
            <li><a data-toggle="tab" href="#Note">File Note </a></li>
            <li><a data-toggle="tab" href="#Agency">Who to Contact </a></li>
            <li><a data-toggle="tab" href="#Fowner">File Owner</a></li>
        </ul>
        <div class="tab-content">

            <div id="Deadline" class="tab-pane active">
                <div class="sidebar-title">
                    <h3> <i class="fa fa-comments-o"></i> Latest Notes</h3>
                    <small><i class="fa fa-tim"></i> You have 10 new message.</small>
                </div>
                <div>
                    <div class="col-lg-12">
                        <label>Deadline date: </label>
                        <div class="input-group input-group">
                            <span class="input-group-addon"></span>
                            <div id="sandbox-container">
                                <div class="input-daterange input-group" id="datepicker">
                                    <input type="text" class="input-sm form-control"  />
                                </div>
                            </div>
                        </div>
                        <label>Category: </label>
                        <div class="input-group input-group">

                            <span class="input-group-addon"></span>
                            <select>
                                <option value="value">options</option>
                            </select>
                        </div>
                        <label>Note:  </label>
                        <div class="input-group input-group">
                            <span class="input-group-addon"></span>
                            <textarea></textarea>
                            <button>@T("add")</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>

Plaza.Web/Views/Shared/_WebFooter.cshtml
<footer class="footer">

    <div class="footer-top">

        <div class="container">

            <div class="row">
                
                <div class="col-xs-12 col-md-4">

                    <p>
                        <img alt="logo-footer" src="/images/home/logo-2.png" width="100" class="logo">
                    </p>
                    <p>
                        @T("")
                    </p>
                    <p>
                        <a target="_blank" href="@T("facebook")"  class="social-icons__link"><i class="fa fa-facebook"></i></a>
                        <a target="_blank" href="@T("Twitter")" class="social-icons__link"><i class="fa fa-twitter"></i></a>
                        <a target="_blank" href="@T("instagram")" class="social-icons__link"><i class="fa fa-instagram"></i></a>
                        
                    </p>

                </div><!-- /.row -->
                
                <div class="col-xs-12 col-md-2">

                    <div class="widget_nav_menu">

                        <h6 class="footer-top__headings">@T("home.ourservice")</h6>
                        <ul>
                            <li class="current-menu-item ">
                                <a href="/home/express">@T("Home.express")</a>
                            </li>
                            <li class="current-menu-item ">
                                <a href="/home/doortodoor">@T("Home.doortodoor")</a>
                            </li>
                            <li class="current-menu-item ">
                                <a href="/home/track">@T("Home.track")</a>
                            </li>
                           
                        </ul>

                    </div><!-- /.widget_nav_menu -->

                </div><!-- /.row -->
                
                <div class="col-xs-12 col-md-6">

                    <h6 class="footer-top__headings">@T("Aboutus")</h6>
                    <p>
                        @T("Aboutus.des")
                    </p>
                    @*<p>
                        <a target="_blank" href="#" class="btn btn-info">BUY CARGOPRESS</a>
                    </p>*@

                </div><!-- /.row -->

            </div><!-- /.row -->

        </div><!-- /.footer -->

    </div><!-- /.footer-top -->

    <div class="footer-bottom">

        <div class="container">

            <div class="footer-bottom__left">
                Developed by <a href="https://www.emarkasoft.com/">E-MARKA SOFT</a>.
            </div>

            <div class="footer-bottom__right">
                Copyright &copy; 2018 @T("home.title"). All rights reserved.
            </div>

        </div><!-- /.container -->

    </div><!-- /.footer-bottom -->

</footer>

Plaza.Web/Views/Shared/_WebHeader.cshtml
@using Autofac;
@using Line.Models;
@using Line.Data;
@{
    var _workcontext = DependencyManager.Scope.Resolve<Line.Services.IWorkContext>();
}
<!-- TOP BAR -->
<div class="top">

    <div class="container">

        <div class="top__tagline"> @Html.Action("LanguageSelector", "Common")</div>

        <nav class="top__menu">
            <ul class="top-navigation js-dropdown">
                @if (_workcontext.CurrentVisitor.IsInCustomerRole(SystemVisitorTypeNames.Members))
                {
                    <li>
                        @Html.ActionLink(T("controlpanal").ToString(), "dashboard", "shipments", new { area = "admin" }, null)
                    </li>
                    <li>
                        <a href="~/Account/logout">@T("Logoff")  </a>
                    </li>
                }
                else
                {
                    <li>
                        <a href="~/Account/login"  target="_blank">@T("home.login")</a>
                    </li>
                }
            </ul>
        </nav>

    </div><!-- /.container -->

</div>
<!-- /.top -->
<!-- HEADER -->
<div class="header__container">

    <div class="container">

        <header class="header">

            <div class="header__logo">
                <a href="/">
                    <img class="img-responsive" width="100" srcset="/images/home/logo-2.png" alt="Smartship" src="@T("logo.url")">
                </a>
                <button data-target="#cargopress-navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                  
                    <span class="navbar-toggle__icon-bar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </span>
                </button>
            </div><!-- /.header__logo -->

            <div class="header__navigation">
                <nav class="collapse navbar-collapse" id="cargopress-navbar-collapse">
                    <ul class="main-navigation js-main-nav js-dropdown">
                        <li class="current-menu-item ">
                            <a href="/">@T("Home")</a>
                        </li>
                        <li class="current-menu-item ">
                            <a href="/home/express">@T("Home.express")</a>
                        </li>
                        <li class="current-menu-item ">
                            <a href="/home/doortodoor">@T("Home.doortodoor")</a>
                        </li>
                        <li class="current-menu-item ">
                            <a href="/home/aboutus">@T("Home.aboutUs")</a>
                        </li>
                        <li class="current-menu-item ">
                            <a href="/home/contactus">@T("Home.callus")</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <!-- /.header__navigation -->

            <div class="header__widgets">

                <div class="widget-icon-box">

                    <div class="icon-box">
                        <i class="fa fa-headphones"></i>
                        <h4 class="icon-box__title">@T("home.callusanytime")</h4>
                        <span class="icon-box__subtitle">@T("home.callusanytime.value")</span>
                    </div>

                </div>

                <div class="widget-icon-box">

                    <div class="icon-box">
                        <i class="fa fa-clock-o"></i>
                        <h4 class="icon-box__title">@T("home.opentime")</h4>
                        <span class="icon-box__subtitle">@T("home.opentime.value")</span>
                    </div>

                </div>

                <div class="widget-icon-box">

                    <div class="icon-box">
                        <i class="fa fa-envelope-o"></i>
                        <h4 class="icon-box__title">@T("home.emailus")</h4>
                        <span class="icon-box__subtitle">@T("home.emailus.value")</span>
                    </div>

                </div>

                <a href="/home/track" target="_self" class="btn btn-info" id="button_requestQuote">@T("home.track")</a>

            </div><!-- /.header__widgets -->

            <div class="header__navigation-widgets">
                <a target="_blank" href="@T("facebook")" class="social-icons__link"><i class="fa fa-facebook"></i></a>
                <a target="_blank" href="@T("Twitter")" class="social-icons__link"><i class="fa fa-twitter"></i></a>
                <a target="_blank" href="@T("instagram")" class="social-icons__link"><i class="fa fa-instagram"></i></a>
            </div>

        </header>

    </div><!-- /.container -->

</div>
<!-- /.header__container -->

Plaza.Web/Views/Shared/_WebLayout.cshtml
</html>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@T("home.title") | @ViewBag.Title</title>
    <!-- Styling -->
    <link href="/cargopress/html/css/style.css" rel="stylesheet">
    <link href="/cargopress/html/css/magnific-popup.css" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Roboto%3A400%2C700%7CSource+Sans+Pro%3A700%2C900&amp;subset=latin" rel="stylesheet">

    <script src="/cargopress/html/js/modernizr.custom.24530.js" type="text/javascript"></script>

    <link rel="shortcut icon" href="/cargopress/html/images/fav.png">

    <script>
        /* Google Map Market Settings */

        var mapMarkers = [
            {
                "id": "1",
                "title": "CargoPress",
                "address": "Changi Airport, Singapore",
                "custompinimage": "images\/pin.png"
            }
        ]
    </script>

</head>
<body>

    <!-- MAIN PAGE CONTAINER -->

    <div class="boxed-container">



        <!-- Navigation -->
        @Html.Partial("_WebHeader")

        <!-- Main view  -->
        @RenderBody()

        @*@Html.Partial("_WebMarks")*@

        @Html.Partial("_WebFooter")


    </div>

    <!-- /.boxed-container -->

    <script src="/cargopress/html/js/jquery-2.1.4.min.js" type="text/javascript"></script>
    <script src="/cargopress/html/js/bootstrap/carousel.js"></script>
    <script src="/cargopress/html/js/bootstrap/transition.js"></script>
    <script src="/cargopress/html/js/bootstrap/button.js"></script>
    <script src="/cargopress/html/js/bootstrap/collapse.js"></script>
    <script src="/cargopress/html/js/bootstrap/validator.js"></script>
    <script src="/cargopress/html/js/underscore.js"></script>
    <script src="https://maps.google.com/maps/api/js?sensor=false"></script>
    <script src="/cargopress/html/js/SimpleMap.js"></script>
    <script src="/cargopress/html/js/NumberCounter.js"></script>
    <script src="/cargopress/html/js/jquery.magnific-popup.min.js"></script>
    <script src="/cargopress/html/js/custom.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

Plaza.Web/Views/Shared/_WebMarks.cshtml
<section class="section section-custom-map-2">
    <section class="section section-default section-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="owl-carousel owl-theme" data-plugin-options='{"items": 6, "autoplay": true, "autoplayTimeout": 3000}'>
                        <div>
                            <img class="img-responsive" src="/HomeTemplate/img/logos/logo-1.png" alt="">
                        </div>
                        <div>
                            <img class="img-responsive" src="/HomeTemplate/img/logos/logo-2.png" alt="">
                        </div>
                        <div>
                            <img class="img-responsive" src="/HomeTemplate/img/logos/logo-3.png" alt="">
                        </div>
                        <div>
                            <img class="img-responsive" src="/HomeTemplate/img/logos/logo-4.png" alt="">
                        </div>
                        <div>
                            <img class="img-responsive" src="/HomeTemplate/img/logos/logo-5.png" alt="">
                        </div>
                        <div>
                            <img class="img-responsive" src="/HomeTemplate/img/logos/logo-6.png" alt="">
                        </div>
                        <div>
                            <img class="img-responsive" src="/HomeTemplate/img/logos/logo-4.png" alt="">
                        </div>
                        <div>
                            <img class="img-responsive" src="/HomeTemplate/img/logos/logo-2.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>

Plaza.Web/Views/Shared/_invoice.cshtml
@{
      Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    <title></title>
</head>
<body>
    @RenderBody()
</body>
</html>